### ISSUE TITLE
Why is the gpu version of PGDS slower than the cpu version?

### ISSUE THREAD

**Issue by keepgoingjkg** [BoChenGroup/PyDPM#27]
Why is the gpu version of PGDS slower than the cpu version? The time those two cost per epoch is about 1.256 to 1.032 seconds. That's very different from other models like PGBN.

**Comment by Dustone-Mu** [comment]
The poor performance of GPU version is caused by model sampler. Specifically, PyDPM does not perform a specific acceleration of the particular Gibbs sampling process in some models like DirBN & PGDS. The details can be found here：[PGDS](http://mingyuanzhou.github.io/Papers/ScheinZhouWallach2016_paper.pdf), [DirBN](https://arxiv.org/pdf/1811.00717.pdf).

In the future, we will consider optimizing them more comprehensively.
